### ISSUE TITLE
How to configure a library using instant for wasm/native

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [sebcrozet/instant#1]
This is going to seem like a dumb question, as I think I am just  misreading your README.

I have a library (called 'flowrlib') that I want to use instant in, as it is compiled for native with one binary, and for wasm for a web app (which is a library, as I'm using wasm-pack etc to load it in web).

This is how I have configured the flowrlib Cargo.toml:
```
[features]
stdweb = [ "instant/stdweb" ]
wasm-bindgen = [ "instant/wasm-bindgen" ]

[dependencies]
instant = { version = "0.1", features = [ "now" ] }
```
(I tried without the stdweb and wasm-bindgen stuff, same problems).

Then I use it in the web library which is compiled to wasm (and hence this compiles flowrlib for wasm also as it is a dependency).

Web library Cargo.toml is thus:
```
[dependencies]
flowrlib = { path = "../../flowrlib", version = "~0.7.0" }
```

When I execute the resulting app in the browser I get the ''Time system call is not implemented by WebAssembly host'' message.

I tried also adding the
```
[features]
stdweb = [ "instant/stdweb" ]
wasm-bindgen = [ "instant/wasm-bindgen" ]
```
in the web-app library, but I can't as it says:
```
Caused by:
|   Features and dependencies cannot have the same name: `wasm-bindgen`
```

as it needs wasm-bindgen as a dependency:
```
[dependencies]
wasm-bindgen = "0.2.25"
```

So, my question is double:
* how to configure my flowrlib library that uses instant, so that it can be used as a dependency by other libraries/binaries with native and wasm targets
* do I need to do anything special in the Cargo.toml of a library consuming 'flowlibr' that is compiled for wasm via wasm-pack or similar

thanks!

**Comment by sebcrozet** [comment]
Hi! If you use `wasm-bindgen`, you need to enable the `wasm-bindgen` feature of `instant`. To do so you can either:

- The simplest solution: `instant = { version = "0.1", features = [ "now", "wasm-bindgen" ] }` in the `Cargo.toml` of `flowrlib` (in which case you don't need the two `[features]` you added.
- Or keep the `[features]` declaration of the `Cargo.toml` of `flowrlib` and enable the `wasm-bindgen` feature of `flowrlib` (which will transitively enable the `wasm-bindgen` feature of `instant`) like so:

```toml
[dependencies]
flowrlib = { path = "../../flowrlib", version = "~0.7.0", features = [ "wasm-bindgen" ] }
```

**Comment by andrewdavidmackenzie** [comment]
Thanks for your help.

I made the changes and  now the error message has changed, so I suspect it's a new problem of mine that I'll investigate. But it only appears when I use instant. If I comment those lines all works fine.

Will let you know what I find.

My flowrlib Cargo.toml has this:
```
[dependencies]
# A std::Instant compatible crate that also supports wasm
instant = { version = "0.1", features = [ "now", "wasm-bindgen" ] }
```

then web-app's one includes:
```
[dependencies]
flowclib = { path = "../../flowclib", version = "~0.7.0" }
flowrlib = { path = "../../flowrlib", version = "~0.7.0" }
flowstdlib = { path = "../../flowstdlib", version = "~0.7.0" }
serde_json = "1.0"
wasm-bindgen = "0.2.25"
wasm-logger = "0.1.4"
log = {version = "0.4.6", features = ["std"]}
webprovider = { path = "../../webprovider", version = "0.1.0"}
```

**Comment by andrewdavidmackenzie** [comment]
Weird. It's another part of my code (in flowrlib) that uses "Duration::new()" (to set a timeout on a channel read).

Browser backtrace:
```
Uncaught (in promise) TypeError: Illegal invocation
    at __wbg_now_12e01413ac259710 (bundle.js:122)
    at instant::wasm::now::h2ba725ccb8d03a96 (:8080/wasm-function[1093]:1)
    at flowrlib::coordinator::Submission::new::ha84e9f0335dcde54 (:8080/wasm-function[157]:404)
    at run (:8080/wasm-function[43]:2310)
    at Module.run (web.js?28c7:7)
    at eval (index.js?ee1c:2)
```

If I comment out *other* lines, in another file, that use Instant and pull it in - it *all* works (in browser).

Leaving the use of 'instant' in (no commented code) and with your instructions for use of instant in Cargo.toml I now get this error....

**Comment by sebcrozet** [comment]
Strange. Is there some steps I can follow/code I can run to reproduce the issue?

**Comment by andrewdavidmackenzie** [comment]
I have not been able to get the wasm test runner working for my project yet, or I would give you a failing test. Here's a description and while you look at it, I'll clone your repo and see if I can add a failing test to it....

Attempt at  minimal reproducible code:


lib1 (flowrlib): 
Cargo.toml
```
instant = { version = "0.1", features = [ "now", "wasm-bindgen" ] }
```

submission.rs
```
use std::time::Duration;

pub struct Submission {
    output_timeout: Duration
}

impl Submission {
    pub fn new() -> Submission {
        Submission {
            output_timeout: Duration::from_secs(1);
        }
    }
}
```

web-app lib - a wasm-pack project following the structure in the rust wasm book:
Cargo.toml
```
...
flowrlib = { path = "../../flowrlib", version = "~0.7.0" }
...
[dependencies.web-sys] # in case this is relevant...
version = "0.3"
features = [
  "Document",
  "Element",
  "HtmlElement",
  "Node",
  "Text",
  "Window",
  "console",
]

```

run.rs:
```
use flowrlib::submission::Submission;

// Called by our JS entry point to run the example.
#[wasm_bindgen]
pub fn run() -> Result<(), JsValue> {
    set_panic_hook();

...
// Code up to here runs fine in browser

    let submission = Submission::new();
// Crashes in the browser when Submission::new() calls Duration::new (or from_sec)
// bundle.js:122 Uncaught (in promise) TypeError: Illegal invocation
//    at __wbg_now_12e01413ac259710 (bundle.js:122)
//    at instant::wasm::now::h2ba725ccb8d03a96 (:8080/wasm-function[1093]:1)
//    at flowrlib::coordinator::Submission::new::ha84e9f0335dcde54 (:8080/wasm-function[157]:404)
//    at run (:8080/wasm-function[43]:2310)
//    at Module.run (web.js?28c7:7)
//    at eval (index.js?ee1c:2)

...

    Ok(())
}
```

**Comment by andrewdavidmackenzie** [comment]
Started with this: but no luck so far, test using Duration passes.
https://github.com/andrewdavidmackenzie/instant

**Comment by andrewdavidmackenzie** [comment]
Added a call to Instant in the test:

```
#[wasm_bindgen_test]
fn duration() {
    let instant = Instant::now();
    let duration = Duration::new(1, 0);
    println!("Instant::now() gives: {:?}", instant);
    assert_eq!(1, duration.as_secs());
}
```

and that causes the test to fail:

```
---- wasm::duration output ----
    error output:
        panicked at 'Time system call is not implemented by WebAssembly host', src/libstd/sys/wasm/mod.rs:304:13

        Stack:

        Error
            at imports.wbg.__wbg_new_59cb74e423758ede (http://127.0.0.1:60605/wasm-bindgen-test:749:34)
            at console_error_panic_hook::Error::new::hd8cc6eab663591c2 (wasm-function[990]:34)
            at console_error_panic_hook::hook_impl::h6d137652cee04f05 (wasm-function[304]:100)
            at console_error_panic_hook::hook::hd453ef50a5c77fd3 (wasm-function[1858]:38)
            at core::ops::function::Fn::call::had4373324a982a95 (wasm-function[1707]:45)
            at std::panicking::rust_panic_with_hook::h12b7239ed4348eae (wasm-function[463]:265)
            at std::panicking::begin_panic::h406f17e92e442d87 (wasm-function[2065]:40)
            at std::sys::wasm::TimeSysCall::perform::he20374f324c69954 (wasm-function[2327]:13)
            at std::sys::wasm::time::Instant::now::h632e5d628b6df99c (wasm-function[2383]:3)
            at std::time::Instant::now::h9ecf1cff307ede73 (wasm-function[2397]:1)



    JS exception that was thrown:
        RuntimeError: unreachable
            at __rust_start_panic (wasm-function[2185]:33)
            at rust_panic (wasm-function[2118]:31)
            at std::panicking::rust_panic_with_hook::h12b7239ed4348eae (wasm-function[463]:304)
            at std::panicking::begin_panic::h406f17e92e442d87 (wasm-function[2065]:40)
            at std::sys::wasm::TimeSysCall::perform::he20374f324c69954 (wasm-function[2327]:13)
            at std::sys::wasm::time::Instant::now::h632e5d628b6df99c (wasm-function[2383]:3)
            at std::time::Instant::now::h9ecf1cff307ede73 (wasm-function[2397]:1)
            at wasm::duration::ha275137b23b163b9 (wasm-function[116]:38)
            at core::ops::function::FnOnce::call_once::h3bbabf3ceb801837 (wasm-function[2013]:22)
            at wasm_bindgen_test::__rt::Context::execute_sync::{{closure}}::h6d4d8e724e1f049a (wasm-function[1484]:22)

failures:

    wasm::duration

test result: FAILED. 0 passed; 1 failed; 0 ignored
console.log div contained:
    panicked at 'Time system call is not implemented by WebAssembly host', src/libstd/sys/wasm/mod.rs:304:13

    Stack:

    Error
        at imports.wbg.__wbg_new_59cb74e423758ede (http://127.0.0.1:60605/wasm-bindgen-test:749:34)
        at console_error_panic_hook::Error::new::hd8cc6eab663591c2 (wasm-function[990]:34)
        at console_error_panic_hook::hook_impl::h6d137652cee04f05 (wasm-function[304]:100)
        at console_error_panic_hook::hook::hd453ef50a5c77fd3 (wasm-function[1858]:38)
        at core::ops::function::Fn::call::had4373324a982a95 (wasm-function[1707]:45)
        at std::panicking::rust_panic_with_hook::h12b7239ed4348eae (wasm-function[463]:265)
        at std::panicking::begin_panic::h406f17e92e442d87 (wasm-function[2065]:40)
        at std::sys::wasm::TimeSysCall::perform::he20374f324c69954 (wasm-function[2327]:13)
        at std::sys::wasm::time::Instant::now::h632e5d628b6df99c (wasm-function[2383]:3)
        at std::time::Instant::now::h9ecf1cff307ede73 (wasm-function[2397]:1)



stderr:

    Finished dev [unoptimized + debuginfo] target(s) in 0.11s
     Running target/wasm32-unknown-unknown/debug/deps/instant-73d6e5f51c901966.wasm
     Running target/wasm32-unknown-unknown/debug/deps/wasm-bd7c09269a44b29e.wasm
error: some tests failed
error: test failed, to rerun pass '--test wasm'
```

I hope that helps

**Comment by andrewdavidmackenzie** [comment]
OK, I got the source of the cause wrong. Now I'm trying to produce a small sample you can use to reproduce it. It is still in the use of Instant::now() it appears, just different erro rmessage.

**Comment by andrewdavidmackenzie** [comment]
I'm tring to make these wasm_bindgen_tests work.
https://github.com/andrewdavidmackenzie/instant

So far, it's still calling the std::time version despite me importing instant::Instant :-(

**Comment by sebcrozet** [comment]
@andrewdavidmackenzie This is because the `wasm-bindgen` feature of `instant` must be enabled to run the test. Using the latest version of `wasm-pack`, the test is run successfully by `wasm-pack test --chrome --headless -- --features wasm-bindgen`.

**Comment by andrewdavidmackenzie** [comment]
Thanks. 

I had:
```wasm-pack 0.5.1```
when I updated to 0.8.1 the test passed as you say.

So, it's not that! :-(  I guess I'll keep investigating.

BTW: Do you want that example test addition as a PR?

**Comment by sebcrozet** [comment]
Yeah, a PR would be great :)

**Comment by andrewdavidmackenzie** [comment]
Since those tests need to be run with "wasm-pack test", I'm not sure what's the recommended way to have them run as part of "cargo test"....or just leave them out and let you add the running of them to your circleci?

**Comment by sebcrozet** [comment]
I think it's best to:
> just leave them out and let you add the running of them to your circleci?

**Comment by andrewdavidmackenzie** [comment]
See
https://github.com/sebcrozet/instant/pull/3

Meanwhile, I'll get back to trying to try and fix my issue :-)

**Comment by andrewdavidmackenzie** [comment]
OK.... 1 day later, a lot of learning of wasm_bindgen_tests, Instant, Duration etc etc.... I put it all back the way it was and it works perfectly :-)

My only guess is that with all this wasm-pack and npm and webpack compiling going on that I don't know much about, that something wasn't being compiled correctly based on the features of the Cargo files....

Sorry to have taken up your time.

Thanks for the crate, and hope the tests are a useful base to build on!

**Comment by sebcrozet** [comment]
Glad to hear it ends up working well! Perhaps the upgread of `wasm-pack` to 0.8.1 had something to do with this?
Anyway, thank you for the PR!
