### ISSUE TITLE
Add `checked_duration_since`

### ISSUE THREAD

**Issue by daniel5151** [sebcrozet/instant#26]
`checked_duration_since` was added in Rust 1.39.

https://doc.rust-lang.org/std/time/struct.Instant.html#method.checked_duration_since

**Comment by d3lm** [comment]
Yup running into the same issue.

**Comment by d3lm** [comment]
Hey, any updates on this? Do you accept a PR? Because I really need this.

**Comment by d3lm** [comment]
Or I suppose we can just do

```
#[inline]
pub fn checked_duration_since(&self, earlier: Instant) -> Option<Duration> {
    self.0.checked_sub(earlier)
}
```

Because that already returns an `Option<Duration>`.
