### ISSUE TITLE
'now' called on an object that does not implement interface Performance

### ISSUE THREAD

**Issue by alanpoon** [sebcrozet/instant#4]
dependencies
i am using wasm-bindgen. 
Here is my instant's dependency:
instant =  {version="0.1.1", features = [ "wasm-bindgen","now" ]}

i got this error 'now' called on an object that does not implement interface Performance in the browser.

**Comment by alanpoon** [comment]
There is no problem using this
web_sys::window()
        .expect("should have a window in this context")
        .performance()
        .expect("performance should be available")
        .now()

**Comment by sebcrozet** [comment]
Hi! On what platform are you running your WASM binary?

**Comment by alanpoon** [comment]
firefox browser on ubuntu 16.04. Does not work on chrome too. However, performance.now() is supported in the browser using javascript

**Comment by sebcrozet** [comment]
Do you have a small project I could run so I can reproduce your problem?

**Comment by hecrj** [comment]
I think the issue is that `performance.now` cannot be invoked without its context:
![image](https://user-images.githubusercontent.com/518289/60294029-be2af400-9920-11e9-9b12-9522a8534e9f.png)

**Comment by TannerRogalsky** [comment]
I am getting a similar error. Both of the current PRs fix it for me.
