### ISSUE TITLE
`SystemTime::elapsed()` is broken

### ISSUE THREAD

**Issue by justinlovinger** [sebcrozet/instant#49]
`self.duration_since(SystemTime::now())`, <https://github.com/sebcrozet/instant/blob/master/src/wasm.rs#L202>, should be `Self::now().duration_since(*self)`, like `Instant`.

**Comment by MingweiSamuel** [comment]
Wow this crate is so amazingly busted

**Comment by sebcrozet** [comment]
This is now fixed in version 0.1.13.
I have now marked the crate as unmaintained in the readme and cargo badge.

**Comment by MingweiSamuel** [comment]
Oh nice!
